/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IRewardDistributorManagerInterface extends ethers.utils.Interface {
  functions: {
    "accumulateRewards(address,address)": FunctionFragment;
    "activateReward(address)": FunctionFragment;
    "removeReward(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "accumulateRewards",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "activateReward",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeReward",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "accumulateRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activateReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeReward",
    data: BytesLike
  ): Result;

  events: {
    "AddReward(address,address,uint256)": EventFragment;
    "DistributorStatusUpdated(address,bool,uint256)": EventFragment;
    "Initialized(address,uint256)": EventFragment;
    "OwnershipAccepted(address,address,uint256)": EventFragment;
    "RemoveReward(address,address,uint256)": EventFragment;
    "TransferControl(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddReward"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DistributorStatusUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipAccepted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemoveReward"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferControl"): EventFragment;
}

export class IRewardDistributorManager extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IRewardDistributorManagerInterface;

  functions: {
    accumulateRewards(
      _from: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "accumulateRewards(address,address)"(
      _from: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    activateReward(
      _tokenAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "activateReward(address)"(
      _tokenAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeReward(
      _tokenAddr: string,
      _distributor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "removeReward(address,address)"(
      _tokenAddr: string,
      _distributor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  accumulateRewards(
    _from: string,
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "accumulateRewards(address,address)"(
    _from: string,
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  activateReward(
    _tokenAddr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "activateReward(address)"(
    _tokenAddr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeReward(
    _tokenAddr: string,
    _distributor: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "removeReward(address,address)"(
    _tokenAddr: string,
    _distributor: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    accumulateRewards(
      _from: string,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "accumulateRewards(address,address)"(
      _from: string,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    activateReward(
      _tokenAddr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "activateReward(address)"(
      _tokenAddr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    removeReward(
      _tokenAddr: string,
      _distributor: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "removeReward(address,address)"(
      _tokenAddr: string,
      _distributor: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    AddReward(
      tokenAddr: null,
      distributor: null,
      timestamp: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { tokenAddr: string; distributor: string; timestamp: BigNumber }
    >;

    DistributorStatusUpdated(
      distributor: null,
      approve: null,
      timestamp: null
    ): TypedEventFilter<
      [string, boolean, BigNumber],
      { distributor: string; approve: boolean; timestamp: BigNumber }
    >;

    Initialized(
      owner: null,
      timestamp: null
    ): TypedEventFilter<
      [string, BigNumber],
      { owner: string; timestamp: BigNumber }
    >;

    OwnershipAccepted(
      prevOwner: null,
      newOwner: null,
      timestamp: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { prevOwner: string; newOwner: string; timestamp: BigNumber }
    >;

    RemoveReward(
      tokenAddr: null,
      distributor: null,
      timestamp: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { tokenAddr: string; distributor: string; timestamp: BigNumber }
    >;

    TransferControl(
      _newTeam: null,
      timestamp: null
    ): TypedEventFilter<
      [string, BigNumber],
      { _newTeam: string; timestamp: BigNumber }
    >;
  };

  estimateGas: {
    accumulateRewards(
      _from: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "accumulateRewards(address,address)"(
      _from: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    activateReward(
      _tokenAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "activateReward(address)"(
      _tokenAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeReward(
      _tokenAddr: string,
      _distributor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "removeReward(address,address)"(
      _tokenAddr: string,
      _distributor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accumulateRewards(
      _from: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "accumulateRewards(address,address)"(
      _from: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    activateReward(
      _tokenAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "activateReward(address)"(
      _tokenAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeReward(
      _tokenAddr: string,
      _distributor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "removeReward(address,address)"(
      _tokenAddr: string,
      _distributor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
